### ISSUE TITLE
Cursor keys movement

### ISSUE THREAD

**Issue by mikezt** [perrada69/memdump#1]
It would be nice to move around the memory without need to press Shift key, because on ZX models without cursor keys it's quite uncomfortable.

**Comment by perrada69** [comment]
Jaké klávesy by jsi chtěl?

6/7/8/9
O/P/Q/A

to by mohlo stačit ne?

**Comment by perrada69** [comment]
pridal jsem tam OPQA ... snad to bude stacit... ;)

**Comment by mikezt** [comment]
Mne stacilo 6/7/8/9. Na 48ckovom rozlozeni (bez kurzovovych klaves) je to pohodlnejsie.
